
MYSQL_USER = 'root'
MYSQL_PASSWORD = '123456'
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_DATABASE = 'stock'

EXCHANGE_SH = "SH"
EXCHANGE_SZ = "SZ"
MARKET_MAIN_A = "MAIN_A"
MARKET_MAIN_B = "MAIN_B"
MARKET_STR_MARK = "STAR_MARK"
MARKET_CHI_NEXT = "CHI_NEXT"
